# ESTE ES UN REPOSITRIO DE PRUEBA
# SERA UTILIZADO PARA TODA LA INFORMACION QUE ME COMPETE EN ELOS ESTUDIOS ACADEMICOS QUE REALICE
# LES COMPARTO MI CONOCIMIENTO 
# ASI COMO MIS AVANCES
# ESPERO SUS RESPUESTAS
# Y QUE SIGA CRECIENDO LA COMUNIDAD DE LEGENDS
# 
# 
